name: Compile and Test on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make `makefile.sh` executable
<<<<<<< HEAD
      run: |
        chmod +x makefile.sh

    - name: Run `makefile.sh` to prepare Makefile
      run: |
        ./makefile.sh delete
=======
      run: chmod +x makefile.sh

    - name: Run `makefile.sh` to prepare Makefile
      run: |
        ./makefile.sh
>>>>>>> 74e49f5ae5a7d912cdff72dc4a1573944672c1e8
        if [ $? -ne 0 ]; then
          echo "::error::makefile.sh failed"
          exit 1
        fi

    - name: Compile using Makefile
      run: |
        cd ComputationalGeometry/6Ex
        make
        if [ $? -ne 0 ]; then
          echo "::error::Compilation failed"
          exit 1
        fi

    - name: Run Tests
      run: |
        cd ComputationalGeometry/6Ex
        if [ ! -f "./a.out" ]; then
          echo "::error::Executable not found: a.out"
          exit 1
        fi

<<<<<<< HEAD
        for file in t/*; do
          echo "Testing with file: $file"

          # Создаём файл ввода
          (echo "0"; echo "$file") | ./a.out
          if [ $? -ne 0 ]; then
            echo "::error::Test failed for $file"
            exit 1
          fi
        done
=======
        # Проверяем, что папка с тестами есть:
        if [ ! -d "t" ]; then
          echo "::error::No directory 't' with test files"
          exit 1
        fi

        for f in t/*; do
          echo "======================="
          echo "Testing with file: $f"

          # Создаём файл с вводом
          echo "0" > input.txt
          echo "$f" >> input.txt

          echo "DEBUG: cat -A input.txt"
          cat -A input.txt  # Посмотреть, нет ли там ^M

          ./a.out < input.txt
          status=$?

          if [ $status -ne 0 ]; then
            echo "::error::Test failed for $f"
            exit 1
          fi
        done
>>>>>>> 74e49f5ae5a7d912cdff72dc4a1573944672c1e8
