name: Compile and Test on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make `makefile.sh` executable
      run: |
        chmod +x makefile.sh

    - name: Compile using makefile.sh
      run: |
        ./makefile.sh
        if [ $? -ne 0 ]; then
          echo "::error::Compilation failed"
          exit 1
        fi

    - name: Run Tests
      run: |
        cd ComputationalGeometry/6Ex
        for file in t/*; do
          echo "Testing with file: $file"

          # Создаём файл ввода
          echo "0" > input.txt
          echo "$file" >> input.txt

          # Запускаем программу
          ./a.out < input.txt
          if [ $? -ne 0 ]; then
            echo "::error::Test failed for $file"
            exit 1
          fi
        done
